ASSUMPTIONS_URL = "https://raw.githubusercontent.com/The-Strategy-Unit/open-plan-docs/refs/heads/main/docs/data/assumptions_register.csv"

ACTIVITY_TYPES = (
    "op",
    "aae",
    "ip_daycase",
    "ip_maternity",
    "ip_wards",
    "ip_procedures_and_theatres",
)

AGGREGATION_SUBSETS = {
    "op": [
        "op_procedures",
        "op_first_attendances",
        "op_follow_up_attendances",
        "op_virtual_attendances",
    ],
    "aae": [
        "adult_major_attendances",
        "adult_minor_attendances",
        "paediatric_major_attendances",
        "paediatric_minor_attendances",
        "resus_attendances",
        "sdec_procedures",
    ],
    "ip_daycase": [
        "adult_daycase_medical",
        "adult_daycase_surgical",
        "daycase_endoscopy",
        "daycase_haem_onc",
        "daycase_renal",
        "paediatric_daycase_medical",
        "paediatric_daycase_surgical",
    ],
    "ip_maternity": [
        "maternity_assessment",
        "maternity_assisted_delivery_nonzerolos",
        "maternity_assisted_delivery_zerolos",
        "maternity_elective_csection_nonzerolos",
        "maternity_elective_csection_zerolos",
        "maternity_nonelective_csection_nonzerolos",
        "maternity_nonelective_csection_zerolos",
        "maternity_normal_delivery_nonzerolos",
        "maternity_normal_delivery_zerolos",
        "maternity_overnight_no_birth",
    ],
    "ip_wards": [
        "adult_elective_medical_nonzerolos",
        "adult_elective_medical_zerolos",
        "adult_elective_surgical_nonzerolos",
        "adult_elective_surgical_zerolos",
        "adult_nonelective_medical_nonzerolos",
        "adult_nonelective_medical_zerolos",
        "adult_nonelective_surgical_nonzerolos",
        "adult_nonelective_surgical_zerolos",
        "paediatric_elective_medical_nonzerolos",
        "paediatric_elective_medical_zerolos",
        "paediatric_elective_surgical_nonzerolos",
        "paediatric_elective_surgical_zerolos",
        "paediatric_nonelective_medical_nonzerolos",
        "paediatric_nonelective_medical_zerolos",
        "paediatric_nonelective_surgical_nonzerolos",
        "paediatric_nonelective_surgical_zerolos",
    ],
}
