name: CodeCov

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          activate-environment: true

      - name: Generate coverage report
        run: >
          uv run --locked --group app python -m pytest
          --cov=.
          --cov-branch
          --cov-report xml:coverage.xml
          tests/unit
          --ignore=tests

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
